apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - local-dns-cm.yaml

helmCharts:
  - name: pihole
    version: 2.34.0
    repo: "https://mojo2600.github.io/pihole-kubernetes/"
    releaseName: pihole
    valuesFile: values.yaml
    namespace: pihole
