# apiVersion: v1
# kind: Service
# metadata:
#   name: pihole-dns-tcp
#   namespace: pihole
#   annotations:
#     metallb.universe.tf/address-pool: public-pool
#     metallb.universe.tf/allow-shared-ip: pihole-dns
# spec:
#   type: LoadBalancer
#   loadBalancerIP: 192.168.1.232
#   selector:
#     app: pihole  # Adjust this to match your PiHole pod labels
#   ports:
#   - name: dns-tcp
#     port: 53
#     targetPort: 53
#     protocol: TCP
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: pihole-dns-udp
#   namespace: pihole
#   annotations:
#     metallb.universe.tf/address-pool: public-pool
#     metallb.universe.tf/allow-shared-ip: pihole-dns
# spec:
#   type: LoadBalancer
#   loadBalancerIP: 192.168.1.232
#   selector:
#     app: pihole  # Adjust this to match your PiHole pod labels
#   ports:
#   - name: dns-udp
#     port: 53
#     targetPort: 53
#     protocol: UDP