serviceDns:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.232
  annotations:
    metallb.universe.tf/address-pool: public-pool
    metallb.universe.tf/allow-shared-ip: pihole-dns

extraVolumes:
  local-dns:
    configMap:
      name: pihole-local-dns

extraVolumeMounts:
  local-dns:
    mountPath: /etc/pihole/hosts/custom.list
    subPath: custom.list
    readOnly: true
