apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storage_class.yaml
  - http-route.yaml

helmCharts:
  - name: longhorn
    version: 1.10.1
    repo: "https://charts.longhorn.io"
    releaseName: longhorn
    namespace: longhorn-system
    valuesFile: values.yaml
