apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - name: tailscale
    version: 1.94.2
    repo: "https://pkgs.tailscale.com/helmcharts"
    releaseName: tailscale
    valuesFile: values.yaml
