# service:
#   annotations:
#     metallb.universe.tf/address-pool: public-pool
#   type: LoadBalancer

topologyInjector:
  enabled: false # Disabled because initial certgen job was failing 

crds:
  gatewayAPI:
    enabled: true
    channel: standard
  envoyGateway:
    enabled: true
