apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Gateway CRDs
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.0/standard-install.yaml


helmCharts:
  - name: traefik-crds
    repo: https://traefik.github.io/charts
    version: 1.13.0
    releaseName: traefik-crds
    namespace: traefik
