apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: envoy-gateway-system

helmCharts:
  - name: gateway-crds-helm
    version: v1.7.0
    repo: oci://docker.io/envoyproxy
    releaseName: envoy-gateway-crds
    valuesFile: values.yaml
