apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Resource files
  # - dashboard_route.yaml

helmCharts:
  - name: traefik
    version: 37.2.0
    repo: "https://traefik.github.io/charts"
    releaseName: traefik
    namespace: traefik
    valuesFile: values.yaml
