apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - https://raw.githubusercontent.com/bitnami-labs/sealed-secrets/main/helm/sealed-secrets/crds/bitnami.com_sealedsecrets.yaml

helmCharts:
  - name: sealed-secrets
    version: 2.15.0
    repo: "https://bitnami-labs.github.io/sealed-secrets"
    releaseName: sealed-secrets
    valuesFile: values.yaml
